trigger: none

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - template: /sdk/spring/pipeline/tests-supported-spring-versions.yml #NOTE: Non-standard template.
        parameters:
          TestName: Spring_IT
          TimeoutInMinutes: 240
          TestOptions: "-DskipSpringITs=false -Dcompiler.failondeprecatedstatus=-"
          TestResourceDirectories:
            - spring/spring-cloud-azure-integration-tests/test-resources/common
      #      - spring/spring-cloud-azure-integration-tests/test-resources/jdbc/mysql
            - spring/spring-cloud-azure-integration-tests/test-resources/appconfiguration
            - spring/spring-cloud-azure-integration-tests/test-resources/cosmos
            - spring/spring-cloud-azure-integration-tests/test-resources/servicebus
            - spring/spring-cloud-azure-integration-tests/test-resources/eventhubs
            - spring/spring-cloud-azure-integration-tests/test-resources/storage
            - spring/spring-cloud-azure-integration-tests/test-resources/keyvault
            - spring/spring-cloud-azure-integration-tests/test-resources/dummy
          Artifacts:
            - name: spring-cloud-azure-integration-tests
              groupId: com.azure.spring
              safeName: springcloudazureintegrationtests
          MatrixConfigs:
            - Name: spring_boot_supported_version_tests
              Path: sdk/spring/pipeline/supported-version-matrix.json
              Selection: sparse
              NonSparseParameters:
                - SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_BOOT_VERSION
              GenerateVMJobs: true
