trigger: none

stages:
  - stage: "InitializeSupportedSpringVersion"
    variables:
      - template: ../../eng/pipelines/templates/variables/globals.yml
    jobs:
      - job: "SetSpringBootAndSpringCloudVersionEnvs"
        steps:
          - template: ../../eng/common/pipelines/templates/steps/sparse-checkout.yml
            parameters:
              Paths:
                - 'sdk/spring/pipeline'
                - 'sdk/spring/scripts'
          - script: |
              python -m pip install termcolor
            displayName: 'Python module install'
          - script: |
              python ./sdk/spring/scripts/compatibility_update_supported_version_matrix_json.py -m 3
            displayName: 'Update test support version'
          - script: |
              python ./sdk/spring/scripts/convert_json_to_env_vars.py ./sdk/spring/pipeline/supported-version-matrix.json
            displayName: 'Convert supported JSON file to Environment Variables'
          - script: echo $(SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_BOOT_VERSION)
            displayName: 'Show Environment Variables'
          - script: echo $(SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_CLOUD_VERSION)
            displayName: 'Show 2Environment Variables'
