trigger: none

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - stage: "Get version that supports Spring Boot and Spring Cloud"
        variables:
            - template: ../../../eng/pipelines/templates/variables/globals.yml
        jobs:
            steps:
              - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
                parameters:
                  Paths:
                    - 'sdk/spring/pipeline'
                    - 'sdk/spring/scripts'
              - script: |
                  python -m pip install termcolor
                displayName: 'Python module install'
              - script: |
                  python ./sdk/spring/scripts/compatibility_update_supported_version_matrix_json.py -m 3
                displayName: 'Update test support version'
              - script: |
                  python convert_json_to_env_vars.py config.json
                  displayName: 'Convert supported JSON file to Environment Variables'
              - powershell: |
                  Write-Host "SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_BOOT_VERSION: $env:SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_BOOT_VERSION"
                  Write-Host "SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_CLOUD_VERSION: $env:SPRING_CLOUD_AZURE_TEST_SUPPORTED_SPRING_CLOUD_VERSION"
